version: 2.1

jobs:
  build:
    docker: 
      - image: 'circleci/node'
    steps:
      - checkout
      - run: npm i
      - run:
          name: 'node build'
          command: npm run build
  test:
    docker: 
      - image: 'circleci/node'
    steps:
      - checkout
      - run: npm i
      - run:
          name: 'node test'
          command: npm run test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build          